name: cron-deploy
on:
    workflow_dispatch:
    push:
        branches-ignore:
            - "**"
    schedule:
        # UTC 20:30, 21:30 ===> JST 5:30, 6:30 (US 16:30)
        - cron: "30 20,21,22 * * *"
env:
    API_URL: ${{secrets.API_URL}}
    SPREADSHEET_URL: ${{secrets.SPREADSHEET_URL}}
    TZ: "America/New_York"
jobs:
    generate:
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-python@v1
              with:
                  python-version: 3.7.11
            - name: Install Dependencies
              run: |
                  python -m pip install --upgrade pip
                  pip install -r requirements.txt
            - name: Run script
              id: changes
              run: |
                  python generator.py
                  git add -N .
                  echo "::set-output name=count::$(git diff --name-only | wc -l)"
            - name: Commit and Push
              env: 
                TZ: "Asia/Tokyo"
              run: |
                  DATE=`date +'%Y-%m-%d %T'`
                  git config --global user.name  "bot"
                  git config --global user.email "bot@example.com"
                  git add .
                  git commit -m "update: ${DATE}"
                  git push
              if: steps.changes.outputs.count > 0
